// Code generated by cmd/aolib-gen from aolib-meta. DO NOT EDIT.

package aolib

// AreaUpdateType is Discriminator for ARUP payloads: 0 = player counts (numbers), 1/2/3 = area metadata strings.
type AreaUpdateType string

const (
	AreaUpdateTypePlayerCount AreaUpdateType = "player_count"
	AreaUpdateTypeStatus AreaUpdateType = "status"
	AreaUpdateTypeCaseManager AreaUpdateType = "case_manager"
	AreaUpdateTypeLocked AreaUpdateType = "locked"
)

var AreaUpdateTypeToWire = map[AreaUpdateType]int{
	AreaUpdateTypePlayerCount: 0,
	AreaUpdateTypeStatus: 1,
	AreaUpdateTypeCaseManager: 2,
	AreaUpdateTypeLocked: 3,
}

var AreaUpdateTypeFromWire = map[int]AreaUpdateType{
	0: AreaUpdateTypePlayerCount,
	1: AreaUpdateTypeStatus,
	2: AreaUpdateTypeCaseManager,
	3: AreaUpdateTypeLocked,
}

// DeskModifier is Desk visibility behavior.
type DeskModifier string

const (
	DeskModifierHidden DeskModifier = "hidden"
	DeskModifierShown DeskModifier = "shown"
	DeskModifierHideDuringPreanim DeskModifier = "hide_during_preanim"
	DeskModifierShowDuringPreanim DeskModifier = "show_during_preanim"
	DeskModifierHideAndCenterDuringPreanim DeskModifier = "hide_and_center_during_preanim"
	DeskModifierShowDuringPreanimThenCenter DeskModifier = "show_during_preanim_then_center"
)

var DeskModifierToWire = map[DeskModifier]int{
	DeskModifierHidden: 0,
	DeskModifierShown: 1,
	DeskModifierHideDuringPreanim: 2,
	DeskModifierShowDuringPreanim: 3,
	DeskModifierHideAndCenterDuringPreanim: 4,
	DeskModifierShowDuringPreanimThenCenter: 5,
}

var DeskModifierFromWire = map[int]DeskModifier{
	0: DeskModifierHidden,
	1: DeskModifierShown,
	2: DeskModifierHideDuringPreanim,
	3: DeskModifierShowDuringPreanim,
	4: DeskModifierHideAndCenterDuringPreanim,
	5: DeskModifierShowDuringPreanimThenCenter,
}

// EmoteModifier is Emote behavior selector. Spec values 3 and 4 are documented as unused.
type EmoteModifier string

const (
	EmoteModifierNoPreanim EmoteModifier = "no_preanim"
	EmoteModifierPreanim EmoteModifier = "preanim"
	EmoteModifierPreanimAndObjection EmoteModifier = "preanim_and_objection"
	EmoteModifierUnused3 EmoteModifier = "unused_3"
	EmoteModifierUnused4 EmoteModifier = "unused_4"
	EmoteModifierZoom EmoteModifier = "zoom"
	EmoteModifierObjectionZoom EmoteModifier = "objection_zoom"
)

var EmoteModifierToWire = map[EmoteModifier]int{
	EmoteModifierNoPreanim: 0,
	EmoteModifierPreanim: 1,
	EmoteModifierPreanimAndObjection: 2,
	EmoteModifierUnused3: 3,
	EmoteModifierUnused4: 4,
	EmoteModifierZoom: 5,
	EmoteModifierObjectionZoom: 6,
}

var EmoteModifierFromWire = map[int]EmoteModifier{
	0: EmoteModifierNoPreanim,
	1: EmoteModifierPreanim,
	2: EmoteModifierPreanimAndObjection,
	3: EmoteModifierUnused3,
	4: EmoteModifierUnused4,
	5: EmoteModifierZoom,
	6: EmoteModifierObjectionZoom,
}

// Flip is Sprite mirroring.
type Flip string

const (
	FlipNone Flip = "none"
	FlipHorizontal Flip = "horizontal"
	FlipVertical Flip = "vertical"
	FlipHorizontalAndVertical Flip = "horizontal_and_vertical"
)

var FlipToWire = map[Flip]int{
	FlipNone: 0,
	FlipHorizontal: 1,
	FlipVertical: 2,
	FlipHorizontalAndVertical: 3,
}

var FlipFromWire = map[int]Flip{
	0: FlipNone,
	1: FlipHorizontal,
	2: FlipVertical,
	3: FlipHorizontalAndVertical,
}

// ShoutModifier is Shout / objection selector.
type ShoutModifier string

const (
	ShoutModifierNone ShoutModifier = "none"
	ShoutModifierHoldIt ShoutModifier = "hold_it"
	ShoutModifierObjection ShoutModifier = "objection"
	ShoutModifierTakeThat ShoutModifier = "take_that"
	ShoutModifierCustom ShoutModifier = "custom"
)

var ShoutModifierToWire = map[ShoutModifier]int{
	ShoutModifierNone: 0,
	ShoutModifierHoldIt: 1,
	ShoutModifierObjection: 2,
	ShoutModifierTakeThat: 3,
	ShoutModifierCustom: 4,
}

var ShoutModifierFromWire = map[int]ShoutModifier{
	0: ShoutModifierNone,
	1: ShoutModifierHoldIt,
	2: ShoutModifierObjection,
	3: ShoutModifierTakeThat,
	4: ShoutModifierCustom,
}

// Side is Character position. Wire values are the lowercase 3-letter codes.
type Side string

const (
	SideDef Side = "def"
	SidePro Side = "pro"
	SideHld Side = "hld"
	SideHlp Side = "hlp"
	SideWit Side = "wit"
	SideJud Side = "jud"
	SideJur Side = "jur"
	SideSea Side = "sea"
)

// TextColor is Chat message text color. `blue` also disables the talking animation.
type TextColor string

const (
	TextColorWhite TextColor = "white"
	TextColorGreen TextColor = "green"
	TextColorRed TextColor = "red"
	TextColorOrange TextColor = "orange"
	TextColorBlue TextColor = "blue"
	TextColorYellow TextColor = "yellow"
	TextColorPink TextColor = "pink"
	TextColorCyan TextColor = "cyan"
	TextColorGrey TextColor = "grey"
	TextColorRainbow TextColor = "rainbow"
)

var TextColorToWire = map[TextColor]int{
	TextColorWhite: 0,
	TextColorGreen: 1,
	TextColorRed: 2,
	TextColorOrange: 3,
	TextColorBlue: 4,
	TextColorYellow: 5,
	TextColorPink: 6,
	TextColorCyan: 7,
	TextColorGrey: 8,
	TextColorRainbow: 9,
}

var TextColorFromWire = map[int]TextColor{
	0: TextColorWhite,
	1: TextColorGreen,
	2: TextColorRed,
	3: TextColorOrange,
	4: TextColorBlue,
	5: TextColorYellow,
	6: TextColorPink,
	7: TextColorCyan,
	8: TextColorGrey,
	9: TextColorRainbow,
}

