// Code generated by cmd/aolib-gen from spec. DO NOT EDIT.

package aolib

// ARUP is 
type ARUP struct {
	UpdateType AreaUpdateType `json:"update_type"`
	UpdateData []string `json:"update_data"`
}

func (p *ARUP) Header() string { return "ARUP" }

func (p *ARUP) Args() []string {
	var args []string
	args = append(args, Itoa(AreaUpdateTypeToWire[p.UpdateType]))
	args = append(args, p.UpdateData...)
	return args
}

func ParseARUP(body []string) (*ARUP, error) {
	p := &ARUP{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.UpdateType = AreaUpdateTypeFromWire[AtoiOrZero(get(cursor))]
	cursor++
	p.UpdateData = body[cursor:]
	cursor = len(body)
	return p, nil
}

// ASS is 
type ASS struct {
	AssetUrl string `json:"asset_url"`
}

func (p *ASS) Header() string { return "ASS" }

func (p *ASS) Args() []string {
	var args []string
	args = append(args, EscapeFanta(p.AssetUrl))
	return args
}

func ParseASS(body []string) (*ASS, error) {
	p := &ASS{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.AssetUrl = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// AUTH is 
type AUTH struct {
	AuthState int `json:"auth_state"`
}

func (p *AUTH) Header() string { return "AUTH" }

func (p *AUTH) Args() []string {
	var args []string
	args = append(args, Itoa(p.AuthState))
	return args
}

func ParseAUTH(body []string) (*AUTH, error) {
	p := &AUTH{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.AuthState = AtoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// Askchaa is 
type Askchaa struct {
}

func (p *Askchaa) Header() string { return "askchaa" }

func (p *Askchaa) Args() []string {
	var args []string
	return args
}

func ParseAskchaa(body []string) (*Askchaa, error) {
	p := &Askchaa{}
	return p, nil
}

// BB is 
type BB struct {
	Message string `json:"message"`
}

func (p *BB) Header() string { return "BB" }

func (p *BB) Args() []string {
	var args []string
	args = append(args, EscapeFanta(p.Message))
	return args
}

func ParseBB(body []string) (*BB, error) {
	p := &BB{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.Message = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// BD is 
type BD struct {
	Reason string `json:"reason"`
}

func (p *BD) Header() string { return "BD" }

func (p *BD) Args() []string {
	var args []string
	args = append(args, EscapeFanta(p.Reason))
	return args
}

func ParseBD(body []string) (*BD, error) {
	p := &BD{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.Reason = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// BN is 
type BN struct {
	Background string `json:"background"`
	Position string `json:"position"`
}

func (p *BN) Header() string { return "BN" }

func (p *BN) Args() []string {
	var args []string
	args = append(args, EscapeFanta(p.Background))
	args = append(args, EscapeFanta(p.Position))
	return args
}

func ParseBN(body []string) (*BN, error) {
	p := &BN{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.Background = UnescapeFanta(get(cursor))
	cursor++
	p.Position = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// CC is 
type CC struct {
	PlayerID int `json:"player_id"`
	CharID int `json:"char_id"`
	CharPassword string `json:"char_password"`
}

func (p *CC) Header() string { return "CC" }

func (p *CC) Args() []string {
	var args []string
	args = append(args, Itoa(p.PlayerID))
	args = append(args, Itoa(p.CharID))
	args = append(args, EscapeFanta(p.CharPassword))
	return args
}

func ParseCC(body []string) (*CC, error) {
	p := &CC{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.PlayerID = AtoiOrZero(get(cursor))
	cursor++
	p.CharID = AtoiOrZero(get(cursor))
	cursor++
	p.CharPassword = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// CH is 
type CH struct {
	CharID int `json:"char_id"`
}

func (p *CH) Header() string { return "CH" }

func (p *CH) Args() []string {
	var args []string
	args = append(args, Itoa(p.CharID))
	return args
}

func ParseCH(body []string) (*CH, error) {
	p := &CH{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.CharID = AtoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// CHECK is 
type CHECK struct {
}

func (p *CHECK) Header() string { return "CHECK" }

func (p *CHECK) Args() []string {
	var args []string
	return args
}

func ParseCHECK(body []string) (*CHECK, error) {
	p := &CHECK{}
	return p, nil
}

// CI is 
type CI struct {
	BatchIndex int `json:"batchIndex"`
	Entries []string `json:"entries"`
}

func (p *CI) Header() string { return "CI" }

func (p *CI) Args() []string {
	var args []string
	args = append(args, Itoa(p.BatchIndex))
	args = append(args, p.Entries...)
	return args
}

func ParseCI(body []string) (*CI, error) {
	p := &CI{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.BatchIndex = AtoiOrZero(get(cursor))
	cursor++
	p.Entries = body[cursor:]
	cursor = len(body)
	return p, nil
}

// CTToClient is 
type CTToClient struct {
	Name string `json:"name"`
	Message string `json:"message"`
	IsFromServer bool `json:"is_from_server"`
}

func (p *CTToClient) Header() string { return "CT" }

func (p *CTToClient) Args() []string {
	var args []string
	args = append(args, EscapeFanta(p.Name))
	args = append(args, EscapeFanta(p.Message))
	args = append(args, BoolToWire(p.IsFromServer))
	return args
}

func ParseCTToClient(body []string) (*CTToClient, error) {
	p := &CTToClient{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.Name = UnescapeFanta(get(cursor))
	cursor++
	p.Message = UnescapeFanta(get(cursor))
	cursor++
	p.IsFromServer = WireToBool(get(cursor))
	cursor++
	return p, nil
}

// CTToServer is 
type CTToServer struct {
	Name string `json:"name"`
	Message string `json:"message"`
}

func (p *CTToServer) Header() string { return "CT" }

func (p *CTToServer) Args() []string {
	var args []string
	args = append(args, EscapeFanta(p.Name))
	args = append(args, EscapeFanta(p.Message))
	return args
}

func ParseCTToServer(body []string) (*CTToServer, error) {
	p := &CTToServer{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.Name = UnescapeFanta(get(cursor))
	cursor++
	p.Message = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// CharsCheck is 
type CharsCheck struct {
	Taken []int `json:"taken"`
}

func (p *CharsCheck) Header() string { return "CharsCheck" }

func (p *CharsCheck) Args() []string {
	var args []string
	args = append(args, IntsToStrs(p.Taken)...)
	return args
}

func ParseCharsCheck(body []string) (*CharsCheck, error) {
	p := &CharsCheck{}
	cursor := 0
	p.Taken = StrsToInts(body[cursor:])
	cursor = len(body)
	return p, nil
}

// DE is 
type DE struct {
	ID int `json:"id"`
}

func (p *DE) Header() string { return "DE" }

func (p *DE) Args() []string {
	var args []string
	args = append(args, Itoa(p.ID))
	return args
}

func ParseDE(body []string) (*DE, error) {
	p := &DE{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.ID = AtoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// DONE is 
type DONE struct {
}

func (p *DONE) Header() string { return "DONE" }

func (p *DONE) Args() []string {
	var args []string
	return args
}

func ParseDONE(body []string) (*DONE, error) {
	p := &DONE{}
	return p, nil
}

// Decryptor is 
type Decryptor struct {
	Value string `json:"value"`
}

func (p *Decryptor) Header() string { return "decryptor" }

func (p *Decryptor) Args() []string {
	var args []string
	args = append(args, EscapeFanta(p.Value))
	return args
}

func ParseDecryptor(body []string) (*Decryptor, error) {
	p := &Decryptor{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.Value = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// EE is 
type EE struct {
	ID int `json:"id"`
	Name string `json:"name"`
	Description string `json:"description"`
	Image string `json:"image"`
}

func (p *EE) Header() string { return "EE" }

func (p *EE) Args() []string {
	var args []string
	args = append(args, Itoa(p.ID))
	args = append(args, EscapeFanta(p.Name))
	args = append(args, EscapeFanta(p.Description))
	args = append(args, EscapeFanta(p.Image))
	return args
}

func ParseEE(body []string) (*EE, error) {
	p := &EE{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.ID = AtoiOrZero(get(cursor))
	cursor++
	p.Name = UnescapeFanta(get(cursor))
	cursor++
	p.Description = UnescapeFanta(get(cursor))
	cursor++
	p.Image = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// EI is 
type EI struct {
	ID int `json:"id"`
	Details string `json:"details"`
}

func (p *EI) Header() string { return "EI" }

func (p *EI) Args() []string {
	var args []string
	args = append(args, Itoa(p.ID))
	args = append(args, EscapeFanta(p.Details))
	return args
}

func ParseEI(body []string) (*EI, error) {
	p := &EI{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.ID = AtoiOrZero(get(cursor))
	cursor++
	p.Details = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// EM is 
type EM struct {
	BatchIndex int `json:"batchIndex"`
	Entries []string `json:"entries"`
}

func (p *EM) Header() string { return "EM" }

func (p *EM) Args() []string {
	var args []string
	args = append(args, Itoa(p.BatchIndex))
	args = append(args, p.Entries...)
	return args
}

func ParseEM(body []string) (*EM, error) {
	p := &EM{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.BatchIndex = AtoiOrZero(get(cursor))
	cursor++
	p.Entries = body[cursor:]
	cursor = len(body)
	return p, nil
}

// FA is 
type FA struct {
	Areas []string `json:"areas"`
}

func (p *FA) Header() string { return "FA" }

func (p *FA) Args() []string {
	var args []string
	args = append(args, p.Areas...)
	return args
}

func ParseFA(body []string) (*FA, error) {
	p := &FA{}
	cursor := 0
	p.Areas = body[cursor:]
	cursor = len(body)
	return p, nil
}

// FL is 
type FL struct {
	Features []string `json:"features"`
}

func (p *FL) Header() string { return "FL" }

func (p *FL) Args() []string {
	var args []string
	args = append(args, p.Features...)
	return args
}

func ParseFL(body []string) (*FL, error) {
	p := &FL{}
	cursor := 0
	p.Features = body[cursor:]
	cursor = len(body)
	return p, nil
}

// FM is 
type FM struct {
	MusicList []string `json:"music_list"`
}

func (p *FM) Header() string { return "FM" }

func (p *FM) Args() []string {
	var args []string
	args = append(args, p.MusicList...)
	return args
}

func ParseFM(body []string) (*FM, error) {
	p := &FM{}
	cursor := 0
	p.MusicList = body[cursor:]
	cursor = len(body)
	return p, nil
}

// HI is 
type HI struct {
	HDID string `json:"hdid"`
}

func (p *HI) Header() string { return "HI" }

func (p *HI) Args() []string {
	var args []string
	args = append(args, EscapeFanta(p.HDID))
	return args
}

func ParseHI(body []string) (*HI, error) {
	p := &HI{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.HDID = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// HPToClient is 
type HPToClient struct {
	Bar int `json:"bar"`
	Value int `json:"value"`
}

func (p *HPToClient) Header() string { return "HP" }

func (p *HPToClient) Args() []string {
	var args []string
	args = append(args, Itoa(p.Bar))
	args = append(args, Itoa(p.Value))
	return args
}

func ParseHPToClient(body []string) (*HPToClient, error) {
	p := &HPToClient{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.Bar = AtoiOrZero(get(cursor))
	cursor++
	p.Value = AtoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// HPToServer is 
type HPToServer struct {
	Bar int `json:"bar"`
	Value int `json:"value"`
}

func (p *HPToServer) Header() string { return "HP" }

func (p *HPToServer) Args() []string {
	var args []string
	args = append(args, Itoa(p.Bar))
	args = append(args, Itoa(p.Value))
	return args
}

func ParseHPToServer(body []string) (*HPToServer, error) {
	p := &HPToServer{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.Bar = AtoiOrZero(get(cursor))
	cursor++
	p.Value = AtoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// IDToClient is 
type IDToClient struct {
	PlayerID int `json:"player_id"`
	Software string `json:"software"`
	Version string `json:"version"`
}

func (p *IDToClient) Header() string { return "ID" }

func (p *IDToClient) Args() []string {
	var args []string
	args = append(args, Itoa(p.PlayerID))
	args = append(args, EscapeFanta(p.Software))
	args = append(args, EscapeFanta(p.Version))
	return args
}

func ParseIDToClient(body []string) (*IDToClient, error) {
	p := &IDToClient{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.PlayerID = AtoiOrZero(get(cursor))
	cursor++
	p.Software = UnescapeFanta(get(cursor))
	cursor++
	p.Version = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// IDToServer is 
type IDToServer struct {
	Software string `json:"software"`
	Version string `json:"version"`
}

func (p *IDToServer) Header() string { return "ID" }

func (p *IDToServer) Args() []string {
	var args []string
	args = append(args, EscapeFanta(p.Software))
	args = append(args, EscapeFanta(p.Version))
	return args
}

func ParseIDToServer(body []string) (*IDToServer, error) {
	p := &IDToServer{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.Software = UnescapeFanta(get(cursor))
	cursor++
	p.Version = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// JD is 
type JD struct {
	State int `json:"state"`
}

func (p *JD) Header() string { return "JD" }

func (p *JD) Args() []string {
	var args []string
	args = append(args, Itoa(p.State))
	return args
}

func ParseJD(body []string) (*JD, error) {
	p := &JD{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.State = AtoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// KB is 
type KB struct {
	Reason string `json:"reason"`
}

func (p *KB) Header() string { return "KB" }

func (p *KB) Args() []string {
	var args []string
	args = append(args, EscapeFanta(p.Reason))
	return args
}

func ParseKB(body []string) (*KB, error) {
	p := &KB{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.Reason = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// KK is 
type KK struct {
	Reason string `json:"reason"`
}

func (p *KK) Header() string { return "KK" }

func (p *KK) Args() []string {
	var args []string
	args = append(args, EscapeFanta(p.Reason))
	return args
}

func ParseKK(body []string) (*KK, error) {
	p := &KK{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.Reason = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// LE is 
type LE struct {
	Evidence []string `json:"evidence"`
}

func (p *LE) Header() string { return "LE" }

func (p *LE) Args() []string {
	var args []string
	args = append(args, p.Evidence...)
	return args
}

func ParseLE(body []string) (*LE, error) {
	p := &LE{}
	cursor := 0
	p.Evidence = body[cursor:]
	cursor = len(body)
	return p, nil
}

// MA is 
type MA struct {
	ID int `json:"id"`
	Duration int `json:"duration"`
	Reason string `json:"reason"`
}

func (p *MA) Header() string { return "MA" }

func (p *MA) Args() []string {
	var args []string
	args = append(args, Itoa(p.ID))
	args = append(args, Itoa(p.Duration))
	args = append(args, EscapeFanta(p.Reason))
	return args
}

func ParseMA(body []string) (*MA, error) {
	p := &MA{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.ID = AtoiOrZero(get(cursor))
	cursor++
	p.Duration = AtoiOrZero(get(cursor))
	cursor++
	p.Reason = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// MCToClient is 
type MCToClient struct {
	Name string `json:"name"`
	CharID int `json:"char_id"`
	Showname string `json:"showname"`
	Looping bool `json:"looping"`
	Channel int `json:"channel"`
	Effects int `json:"effects"`
}

func (p *MCToClient) Header() string { return "MC" }

func (p *MCToClient) Args() []string {
	var args []string
	args = append(args, EscapeFanta(p.Name))
	args = append(args, Itoa(p.CharID))
	args = append(args, EscapeFanta(p.Showname))
	args = append(args, BoolToWire(p.Looping))
	args = append(args, Itoa(p.Channel))
	args = append(args, Itoa(p.Effects))
	return args
}

func ParseMCToClient(body []string) (*MCToClient, error) {
	p := &MCToClient{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.Name = UnescapeFanta(get(cursor))
	cursor++
	p.CharID = AtoiOrZero(get(cursor))
	cursor++
	p.Showname = UnescapeFanta(get(cursor))
	cursor++
	p.Looping = WireToBool(get(cursor))
	cursor++
	p.Channel = AtoiOrZero(get(cursor))
	cursor++
	p.Effects = AtoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// MCToServer is 
type MCToServer struct {
	Name string `json:"name"`
	CharID int `json:"char_id"`
	Showname string `json:"showname"`
	Effects int `json:"effects"`
}

func (p *MCToServer) Header() string { return "MC" }

func (p *MCToServer) Args() []string {
	var args []string
	args = append(args, EscapeFanta(p.Name))
	args = append(args, Itoa(p.CharID))
	args = append(args, EscapeFanta(p.Showname))
	args = append(args, Itoa(p.Effects))
	return args
}

func ParseMCToServer(body []string) (*MCToServer, error) {
	p := &MCToServer{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.Name = UnescapeFanta(get(cursor))
	cursor++
	p.CharID = AtoiOrZero(get(cursor))
	cursor++
	p.Showname = UnescapeFanta(get(cursor))
	cursor++
	p.Effects = AtoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// MSToClient is 
type MSToClient struct {
	DeskModifier DeskModifier `json:"desk_modifier"`
	Preanim string `json:"preanim"`
	Character string `json:"character"`
	Emote string `json:"emote"`
	Message string `json:"message"`
	Side Side `json:"side"`
	SfxName string `json:"sfx_name"`
	EmoteModifier EmoteModifier `json:"emote_modifier"`
	CharID int `json:"char_id"`
	SfxDelay int `json:"sfx_delay"`
	ShoutModifier ShoutModifier `json:"shout_modifier"`
	EvidenceID int `json:"evidence_id"`
	Flip Flip `json:"flip"`
	Realization bool `json:"realization"`
	TextColor TextColor `json:"text_color"`
	Showname string `json:"showname"`
	PairedCharID int `json:"paired_charid"`
	PairedName string `json:"paired_name"`
	PairedEmote string `json:"paired_emote"`
	Offset Offset `json:"offset"`
	PairedOffset Offset `json:"paired_offset"`
	PairedFlip Flip `json:"paired_flip"`
	NoninterruptingPreanim bool `json:"noninterrupting_preanim"`
	SfxLooping bool `json:"sfx_looping"`
	Screenshake bool `json:"screenshake"`
	FramesShake string `json:"frames_shake"`
	FramesRealization string `json:"frames_realization"`
	FramesSfx string `json:"frames_sfx"`
	Additive bool `json:"additive"`
	Effect string `json:"effect"`
}

func (p *MSToClient) Header() string { return "MS" }

func (p *MSToClient) Args() []string {
	var args []string
	args = append(args, Itoa(DeskModifierToWire[p.DeskModifier]))
	args = append(args, EscapeFanta(p.Preanim))
	args = append(args, EscapeFanta(p.Character))
	args = append(args, EscapeFanta(p.Emote))
	args = append(args, EscapeFanta(p.Message))
	args = append(args, string(p.Side))
	args = append(args, EscapeFanta(p.SfxName))
	args = append(args, Itoa(EmoteModifierToWire[p.EmoteModifier]))
	args = append(args, Itoa(p.CharID))
	args = append(args, Itoa(p.SfxDelay))
	args = append(args, Itoa(ShoutModifierToWire[p.ShoutModifier]))
	args = append(args, Itoa(p.EvidenceID))
	args = append(args, Itoa(FlipToWire[p.Flip]))
	args = append(args, BoolToWire(p.Realization))
	args = append(args, Itoa(TextColorToWire[p.TextColor]))
	args = append(args, EscapeFanta(p.Showname))
	args = append(args, Itoa(p.PairedCharID))
	args = append(args, EscapeFanta(p.PairedName))
	args = append(args, EscapeFanta(p.PairedEmote))
	args = append(args, OffsetToWire(p.Offset))
	args = append(args, OffsetToWire(p.PairedOffset))
	args = append(args, Itoa(FlipToWire[p.PairedFlip]))
	args = append(args, BoolToWire(p.NoninterruptingPreanim))
	args = append(args, BoolToWire(p.SfxLooping))
	args = append(args, BoolToWire(p.Screenshake))
	args = append(args, EscapeFanta(p.FramesShake))
	args = append(args, EscapeFanta(p.FramesRealization))
	args = append(args, EscapeFanta(p.FramesSfx))
	args = append(args, BoolToWire(p.Additive))
	args = append(args, EscapeFanta(p.Effect))
	return args
}

func ParseMSToClient(body []string) (*MSToClient, error) {
	p := &MSToClient{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.DeskModifier = DeskModifierFromWire[AtoiOrZero(get(cursor))]
	cursor++
	p.Preanim = UnescapeFanta(get(cursor))
	cursor++
	p.Character = UnescapeFanta(get(cursor))
	cursor++
	p.Emote = UnescapeFanta(get(cursor))
	cursor++
	p.Message = UnescapeFanta(get(cursor))
	cursor++
	p.Side = Side(get(cursor))
	cursor++
	p.SfxName = UnescapeFanta(get(cursor))
	cursor++
	p.EmoteModifier = EmoteModifierFromWire[AtoiOrZero(get(cursor))]
	cursor++
	p.CharID = AtoiOrZero(get(cursor))
	cursor++
	p.SfxDelay = AtoiOrZero(get(cursor))
	cursor++
	p.ShoutModifier = ShoutModifierFromWire[AtoiOrZero(get(cursor))]
	cursor++
	p.EvidenceID = AtoiOrZero(get(cursor))
	cursor++
	p.Flip = FlipFromWire[AtoiOrZero(get(cursor))]
	cursor++
	p.Realization = WireToBool(get(cursor))
	cursor++
	p.TextColor = TextColorFromWire[AtoiOrZero(get(cursor))]
	cursor++
	p.Showname = UnescapeFanta(get(cursor))
	cursor++
	p.PairedCharID = AtoiOrZero(get(cursor))
	cursor++
	p.PairedName = UnescapeFanta(get(cursor))
	cursor++
	p.PairedEmote = UnescapeFanta(get(cursor))
	cursor++
	p.Offset = OffsetFromWire(get(cursor))
	cursor++
	p.PairedOffset = OffsetFromWire(get(cursor))
	cursor++
	p.PairedFlip = FlipFromWire[AtoiOrZero(get(cursor))]
	cursor++
	p.NoninterruptingPreanim = WireToBool(get(cursor))
	cursor++
	p.SfxLooping = WireToBool(get(cursor))
	cursor++
	p.Screenshake = WireToBool(get(cursor))
	cursor++
	p.FramesShake = UnescapeFanta(get(cursor))
	cursor++
	p.FramesRealization = UnescapeFanta(get(cursor))
	cursor++
	p.FramesSfx = UnescapeFanta(get(cursor))
	cursor++
	p.Additive = WireToBool(get(cursor))
	cursor++
	p.Effect = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// MSToServer is 
type MSToServer struct {
	DeskModifier DeskModifier `json:"desk_modifier"`
	Preanim string `json:"preanim"`
	Character string `json:"character"`
	Emote string `json:"emote"`
	Message string `json:"message"`
	Side Side `json:"side"`
	SfxName string `json:"sfx_name"`
	EmoteModifier EmoteModifier `json:"emote_modifier"`
	CharID int `json:"char_id"`
	SfxDelay int `json:"sfx_delay"`
	ShoutModifier ShoutModifier `json:"shout_modifier"`
	EvidenceID int `json:"evidence_id"`
	Flip Flip `json:"flip"`
	Realization bool `json:"realization"`
	TextColor TextColor `json:"text_color"`
	Showname string `json:"showname"`
	PairedCharID int `json:"paired_charid"`
	Offset Offset `json:"offset"`
	NoninterruptingPreanim bool `json:"noninterrupting_preanim"`
	SfxLooping bool `json:"sfx_looping"`
	Screenshake bool `json:"screenshake"`
	FramesShake string `json:"frames_shake"`
	FramesRealization string `json:"frames_realization"`
	FramesSfx string `json:"frames_sfx"`
	Additive bool `json:"additive"`
	Effect string `json:"effect"`
}

func (p *MSToServer) Header() string { return "MS" }

func (p *MSToServer) Args() []string {
	var args []string
	args = append(args, Itoa(DeskModifierToWire[p.DeskModifier]))
	args = append(args, EscapeFanta(p.Preanim))
	args = append(args, EscapeFanta(p.Character))
	args = append(args, EscapeFanta(p.Emote))
	args = append(args, EscapeFanta(p.Message))
	args = append(args, string(p.Side))
	args = append(args, EscapeFanta(p.SfxName))
	args = append(args, Itoa(EmoteModifierToWire[p.EmoteModifier]))
	args = append(args, Itoa(p.CharID))
	args = append(args, Itoa(p.SfxDelay))
	args = append(args, Itoa(ShoutModifierToWire[p.ShoutModifier]))
	args = append(args, Itoa(p.EvidenceID))
	args = append(args, Itoa(FlipToWire[p.Flip]))
	args = append(args, BoolToWire(p.Realization))
	args = append(args, Itoa(TextColorToWire[p.TextColor]))
	args = append(args, EscapeFanta(p.Showname))
	args = append(args, Itoa(p.PairedCharID))
	args = append(args, OffsetToWire(p.Offset))
	args = append(args, BoolToWire(p.NoninterruptingPreanim))
	args = append(args, BoolToWire(p.SfxLooping))
	args = append(args, BoolToWire(p.Screenshake))
	args = append(args, EscapeFanta(p.FramesShake))
	args = append(args, EscapeFanta(p.FramesRealization))
	args = append(args, EscapeFanta(p.FramesSfx))
	args = append(args, BoolToWire(p.Additive))
	args = append(args, EscapeFanta(p.Effect))
	return args
}

func ParseMSToServer(body []string) (*MSToServer, error) {
	p := &MSToServer{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.DeskModifier = DeskModifierFromWire[AtoiOrZero(get(cursor))]
	cursor++
	p.Preanim = UnescapeFanta(get(cursor))
	cursor++
	p.Character = UnescapeFanta(get(cursor))
	cursor++
	p.Emote = UnescapeFanta(get(cursor))
	cursor++
	p.Message = UnescapeFanta(get(cursor))
	cursor++
	p.Side = Side(get(cursor))
	cursor++
	p.SfxName = UnescapeFanta(get(cursor))
	cursor++
	p.EmoteModifier = EmoteModifierFromWire[AtoiOrZero(get(cursor))]
	cursor++
	p.CharID = AtoiOrZero(get(cursor))
	cursor++
	p.SfxDelay = AtoiOrZero(get(cursor))
	cursor++
	p.ShoutModifier = ShoutModifierFromWire[AtoiOrZero(get(cursor))]
	cursor++
	p.EvidenceID = AtoiOrZero(get(cursor))
	cursor++
	p.Flip = FlipFromWire[AtoiOrZero(get(cursor))]
	cursor++
	p.Realization = WireToBool(get(cursor))
	cursor++
	p.TextColor = TextColorFromWire[AtoiOrZero(get(cursor))]
	cursor++
	p.Showname = UnescapeFanta(get(cursor))
	cursor++
	p.PairedCharID = AtoiOrZero(get(cursor))
	cursor++
	p.Offset = OffsetFromWire(get(cursor))
	cursor++
	p.NoninterruptingPreanim = WireToBool(get(cursor))
	cursor++
	p.SfxLooping = WireToBool(get(cursor))
	cursor++
	p.Screenshake = WireToBool(get(cursor))
	cursor++
	p.FramesShake = UnescapeFanta(get(cursor))
	cursor++
	p.FramesRealization = UnescapeFanta(get(cursor))
	cursor++
	p.FramesSfx = UnescapeFanta(get(cursor))
	cursor++
	p.Additive = WireToBool(get(cursor))
	cursor++
	p.Effect = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// PE is 
type PE struct {
	Name string `json:"name"`
	Description string `json:"description"`
	Image string `json:"image"`
}

func (p *PE) Header() string { return "PE" }

func (p *PE) Args() []string {
	var args []string
	args = append(args, EscapeFanta(p.Name))
	args = append(args, EscapeFanta(p.Description))
	args = append(args, EscapeFanta(p.Image))
	return args
}

func ParsePE(body []string) (*PE, error) {
	p := &PE{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.Name = UnescapeFanta(get(cursor))
	cursor++
	p.Description = UnescapeFanta(get(cursor))
	cursor++
	p.Image = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// PN is 
type PN struct {
	PlayerCount int `json:"player_count"`
	MaxPlayers int `json:"max_players"`
	ServerDescription string `json:"server_description"`
}

func (p *PN) Header() string { return "PN" }

func (p *PN) Args() []string {
	var args []string
	args = append(args, Itoa(p.PlayerCount))
	args = append(args, Itoa(p.MaxPlayers))
	args = append(args, EscapeFanta(p.ServerDescription))
	return args
}

func ParsePN(body []string) (*PN, error) {
	p := &PN{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.PlayerCount = AtoiOrZero(get(cursor))
	cursor++
	p.MaxPlayers = AtoiOrZero(get(cursor))
	cursor++
	p.ServerDescription = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// PR is 
type PR struct {
	ID int `json:"id"`
	Type int `json:"type"`
}

func (p *PR) Header() string { return "PR" }

func (p *PR) Args() []string {
	var args []string
	args = append(args, Itoa(p.ID))
	args = append(args, Itoa(p.Type))
	return args
}

func ParsePR(body []string) (*PR, error) {
	p := &PR{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.ID = AtoiOrZero(get(cursor))
	cursor++
	p.Type = AtoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// PU is 
type PU struct {
	ID int `json:"id"`
	Type int `json:"type"`
	Data string `json:"data"`
}

func (p *PU) Header() string { return "PU" }

func (p *PU) Args() []string {
	var args []string
	args = append(args, Itoa(p.ID))
	args = append(args, Itoa(p.Type))
	args = append(args, EscapeFanta(p.Data))
	return args
}

func ParsePU(body []string) (*PU, error) {
	p := &PU{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.ID = AtoiOrZero(get(cursor))
	cursor++
	p.Type = AtoiOrZero(get(cursor))
	cursor++
	p.Data = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// PV is 
type PV struct {
	PlayerID int `json:"player_id"`
	CharID int `json:"char_id"`
}

func (p *PV) Header() string { return "PV" }

func (p *PV) Args() []string {
	var args []string
	args = append(args, Itoa(p.PlayerID))
	args = append(args, "CID")
	args = append(args, Itoa(p.CharID))
	return args
}

func ParsePV(body []string) (*PV, error) {
	p := &PV{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.PlayerID = AtoiOrZero(get(cursor))
	cursor++
	cursor++ // const slot
	p.CharID = AtoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// RC is 
type RC struct {
}

func (p *RC) Header() string { return "RC" }

func (p *RC) Args() []string {
	var args []string
	return args
}

func ParseRC(body []string) (*RC, error) {
	p := &RC{}
	return p, nil
}

// RD is 
type RD struct {
}

func (p *RD) Header() string { return "RD" }

func (p *RD) Args() []string {
	var args []string
	return args
}

func ParseRD(body []string) (*RD, error) {
	p := &RD{}
	return p, nil
}

// RM is 
type RM struct {
}

func (p *RM) Header() string { return "RM" }

func (p *RM) Args() []string {
	var args []string
	return args
}

func ParseRM(body []string) (*RM, error) {
	p := &RM{}
	return p, nil
}

// RMC is 
type RMC struct {
	ToTime string `json:"toTime"`
}

func (p *RMC) Header() string { return "RMC" }

func (p *RMC) Args() []string {
	var args []string
	args = append(args, EscapeFanta(p.ToTime))
	return args
}

func ParseRMC(body []string) (*RMC, error) {
	p := &RMC{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.ToTime = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// RTToClient is 
type RTToClient struct {
	Animation string `json:"animation"`
	JudgeID int `json:"judgeId"`
}

func (p *RTToClient) Header() string { return "RT" }

func (p *RTToClient) Args() []string {
	var args []string
	args = append(args, EscapeFanta(p.Animation))
	args = append(args, Itoa(p.JudgeID))
	return args
}

func ParseRTToClient(body []string) (*RTToClient, error) {
	p := &RTToClient{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.Animation = UnescapeFanta(get(cursor))
	cursor++
	p.JudgeID = AtoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// RTToServer is 
type RTToServer struct {
	Animation string `json:"animation"`
	JudgeID int `json:"judgeId"`
}

func (p *RTToServer) Header() string { return "RT" }

func (p *RTToServer) Args() []string {
	var args []string
	args = append(args, EscapeFanta(p.Animation))
	args = append(args, Itoa(p.JudgeID))
	return args
}

func ParseRTToServer(body []string) (*RTToServer, error) {
	p := &RTToServer{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.Animation = UnescapeFanta(get(cursor))
	cursor++
	p.JudgeID = AtoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// SC is 
type SC struct {
	CharData []string `json:"char_data"`
}

func (p *SC) Header() string { return "SC" }

func (p *SC) Args() []string {
	var args []string
	args = append(args, p.CharData...)
	return args
}

func ParseSC(body []string) (*SC, error) {
	p := &SC{}
	cursor := 0
	p.CharData = body[cursor:]
	cursor = len(body)
	return p, nil
}

// SI is 
type SI struct {
	CharCount int `json:"char_count"`
	EviCount int `json:"evi_count"`
	MusCount int `json:"mus_count"`
}

func (p *SI) Header() string { return "SI" }

func (p *SI) Args() []string {
	var args []string
	args = append(args, Itoa(p.CharCount))
	args = append(args, Itoa(p.EviCount))
	args = append(args, Itoa(p.MusCount))
	return args
}

func ParseSI(body []string) (*SI, error) {
	p := &SI{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.CharCount = AtoiOrZero(get(cursor))
	cursor++
	p.EviCount = AtoiOrZero(get(cursor))
	cursor++
	p.MusCount = AtoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// SM is 
type SM struct {
	MusicList []string `json:"music_list"`
}

func (p *SM) Header() string { return "SM" }

func (p *SM) Args() []string {
	var args []string
	args = append(args, p.MusicList...)
	return args
}

func ParseSM(body []string) (*SM, error) {
	p := &SM{}
	cursor := 0
	p.MusicList = body[cursor:]
	cursor = len(body)
	return p, nil
}

// SP is 
type SP struct {
	Side Side `json:"side"`
}

func (p *SP) Header() string { return "SP" }

func (p *SP) Args() []string {
	var args []string
	args = append(args, string(p.Side))
	return args
}

func ParseSP(body []string) (*SP, error) {
	p := &SP{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.Side = Side(get(cursor))
	cursor++
	return p, nil
}

// TI is 
type TI struct {
	TimerID int `json:"timer_id"`
	Command int `json:"command"`
	Time int `json:"time"`
}

func (p *TI) Header() string { return "TI" }

func (p *TI) Args() []string {
	var args []string
	args = append(args, Itoa(p.TimerID))
	args = append(args, Itoa(p.Command))
	args = append(args, Itoa(p.Time))
	return args
}

func ParseTI(body []string) (*TI, error) {
	p := &TI{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.TimerID = AtoiOrZero(get(cursor))
	cursor++
	p.Command = AtoiOrZero(get(cursor))
	cursor++
	p.Time = AtoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// VS_AUDIO is 
type VS_AUDIO struct {
	FromUID int `json:"fromUid"`
	Payload string `json:"payload"`
}

func (p *VS_AUDIO) Header() string { return "VS_AUDIO" }

func (p *VS_AUDIO) Args() []string {
	var args []string
	args = append(args, Itoa(p.FromUID))
	args = append(args, EscapeFanta(p.Payload))
	return args
}

func ParseVS_AUDIO(body []string) (*VS_AUDIO, error) {
	p := &VS_AUDIO{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.FromUID = AtoiOrZero(get(cursor))
	cursor++
	p.Payload = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// VS_CAPS is 
type VS_CAPS struct {
	Enabled bool `json:"enabled"`
	PttOnly bool `json:"pttOnly"`
	MaxPeers int `json:"maxPeers"`
	Codec string `json:"codec"`
	SampleRate int `json:"sampleRate"`
	FrameMs int `json:"frameMs"`
	MaxFrameBytes int `json:"maxFrameBytes"`
}

func (p *VS_CAPS) Header() string { return "VS_CAPS" }

func (p *VS_CAPS) Args() []string {
	var args []string
	args = append(args, BoolToWire(p.Enabled))
	args = append(args, BoolToWire(p.PttOnly))
	args = append(args, Itoa(p.MaxPeers))
	args = append(args, EscapeFanta(p.Codec))
	args = append(args, Itoa(p.SampleRate))
	args = append(args, Itoa(p.FrameMs))
	args = append(args, Itoa(p.MaxFrameBytes))
	return args
}

func ParseVS_CAPS(body []string) (*VS_CAPS, error) {
	p := &VS_CAPS{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.Enabled = WireToBool(get(cursor))
	cursor++
	p.PttOnly = WireToBool(get(cursor))
	cursor++
	p.MaxPeers = AtoiOrZero(get(cursor))
	cursor++
	p.Codec = UnescapeFanta(get(cursor))
	cursor++
	p.SampleRate = AtoiOrZero(get(cursor))
	cursor++
	p.FrameMs = AtoiOrZero(get(cursor))
	cursor++
	p.MaxFrameBytes = AtoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// VS_FRAME is 
type VS_FRAME struct {
	Payload string `json:"payload"`
}

func (p *VS_FRAME) Header() string { return "VS_FRAME" }

func (p *VS_FRAME) Args() []string {
	var args []string
	args = append(args, EscapeFanta(p.Payload))
	return args
}

func ParseVS_FRAME(body []string) (*VS_FRAME, error) {
	p := &VS_FRAME{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.Payload = UnescapeFanta(get(cursor))
	cursor++
	return p, nil
}

// VS_JOINToClient is 
type VS_JOINToClient struct {
	UID int `json:"uid"`
}

func (p *VS_JOINToClient) Header() string { return "VS_JOIN" }

func (p *VS_JOINToClient) Args() []string {
	var args []string
	args = append(args, Itoa(p.UID))
	return args
}

func ParseVS_JOINToClient(body []string) (*VS_JOINToClient, error) {
	p := &VS_JOINToClient{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.UID = AtoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// VS_JOINToServer is 
type VS_JOINToServer struct {
}

func (p *VS_JOINToServer) Header() string { return "VS_JOIN" }

func (p *VS_JOINToServer) Args() []string {
	var args []string
	return args
}

func ParseVS_JOINToServer(body []string) (*VS_JOINToServer, error) {
	p := &VS_JOINToServer{}
	return p, nil
}

// VS_LEAVEToClient is 
type VS_LEAVEToClient struct {
	UID int `json:"uid"`
}

func (p *VS_LEAVEToClient) Header() string { return "VS_LEAVE" }

func (p *VS_LEAVEToClient) Args() []string {
	var args []string
	args = append(args, Itoa(p.UID))
	return args
}

func ParseVS_LEAVEToClient(body []string) (*VS_LEAVEToClient, error) {
	p := &VS_LEAVEToClient{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.UID = AtoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// VS_LEAVEToServer is 
type VS_LEAVEToServer struct {
}

func (p *VS_LEAVEToServer) Header() string { return "VS_LEAVE" }

func (p *VS_LEAVEToServer) Args() []string {
	var args []string
	return args
}

func ParseVS_LEAVEToServer(body []string) (*VS_LEAVEToServer, error) {
	p := &VS_LEAVEToServer{}
	return p, nil
}

// VS_PEERS is 
type VS_PEERS struct {
	Uids []int `json:"uids"`
}

func (p *VS_PEERS) Header() string { return "VS_PEERS" }

func (p *VS_PEERS) Args() []string {
	var args []string
	args = append(args, IntsToStrs(p.Uids)...)
	return args
}

func ParseVS_PEERS(body []string) (*VS_PEERS, error) {
	p := &VS_PEERS{}
	cursor := 0
	p.Uids = StrsToInts(body[cursor:])
	cursor = len(body)
	return p, nil
}

// VS_SPEAKToClient is 
type VS_SPEAKToClient struct {
	UID int `json:"uid"`
	On bool `json:"on"`
}

func (p *VS_SPEAKToClient) Header() string { return "VS_SPEAK" }

func (p *VS_SPEAKToClient) Args() []string {
	var args []string
	args = append(args, Itoa(p.UID))
	args = append(args, BoolToWire(p.On))
	return args
}

func ParseVS_SPEAKToClient(body []string) (*VS_SPEAKToClient, error) {
	p := &VS_SPEAKToClient{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.UID = AtoiOrZero(get(cursor))
	cursor++
	p.On = WireToBool(get(cursor))
	cursor++
	return p, nil
}

// VS_SPEAKToServer is 
type VS_SPEAKToServer struct {
	On bool `json:"on"`
}

func (p *VS_SPEAKToServer) Header() string { return "VS_SPEAK" }

func (p *VS_SPEAKToServer) Args() []string {
	var args []string
	args = append(args, BoolToWire(p.On))
	return args
}

func ParseVS_SPEAKToServer(body []string) (*VS_SPEAKToServer, error) {
	p := &VS_SPEAKToServer{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.On = WireToBool(get(cursor))
	cursor++
	return p, nil
}

// ZZToClient is 
type ZZToClient struct {
	Reason string `json:"reason"`
	Target int `json:"target"`
}

func (p *ZZToClient) Header() string { return "ZZ" }

func (p *ZZToClient) Args() []string {
	var args []string
	args = append(args, EscapeFanta(p.Reason))
	args = append(args, Itoa(p.Target))
	return args
}

func ParseZZToClient(body []string) (*ZZToClient, error) {
	p := &ZZToClient{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.Reason = UnescapeFanta(get(cursor))
	cursor++
	p.Target = AtoiOrZero(get(cursor))
	cursor++
	return p, nil
}

// ZZToServer is 
type ZZToServer struct {
	Reason string `json:"reason"`
	Target int `json:"target"`
}

func (p *ZZToServer) Header() string { return "ZZ" }

func (p *ZZToServer) Args() []string {
	var args []string
	args = append(args, EscapeFanta(p.Reason))
	args = append(args, Itoa(p.Target))
	return args
}

func ParseZZToServer(body []string) (*ZZToServer, error) {
	p := &ZZToServer{}
	get := func(i int) string { if i < len(body) { return body[i] }; return "" }
	cursor := 0
	p.Reason = UnescapeFanta(get(cursor))
	cursor++
	p.Target = AtoiOrZero(get(cursor))
	cursor++
	return p, nil
}

